In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

In [6]:
iris_data = pd.read_csv('iris.data', names=['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class'])

In [7]:
iris_data.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [13]:
X = iris_data.iloc[:,:4]
y = iris_data.iloc[:,4]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: class, dtype: object

# Cross-Validation

In [14]:
n_values = [1,3,5,7,9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35]
for i in n_values:
  classifier = KNeighborsClassifier(n_neighbors=i)
  scores = cross_val_score(classifier, X, y, cv=5)
  # print(scores)
  print("\n K = %d have %0.2f mean accuracy\n" % (i,scores.mean()))


 K = 1 have 0.96 mean accuracy


 K = 3 have 0.97 mean accuracy


 K = 5 have 0.97 mean accuracy


 K = 7 have 0.98 mean accuracy


 K = 9 have 0.97 mean accuracy


 K = 11 have 0.98 mean accuracy


 K = 13 have 0.97 mean accuracy


 K = 15 have 0.97 mean accuracy


 K = 17 have 0.97 mean accuracy


 K = 19 have 0.97 mean accuracy


 K = 21 have 0.97 mean accuracy


 K = 23 have 0.96 mean accuracy


 K = 25 have 0.96 mean accuracy


 K = 27 have 0.95 mean accuracy


 K = 29 have 0.93 mean accuracy


 K = 31 have 0.93 mean accuracy


 K = 33 have 0.94 mean accuracy


 K = 35 have 0.95 mean accuracy



# F-measure

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

for k in [1, 3, 5, 7, 9,  11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35]:
  knn = KNeighborsClassifier(n_neighbors=k)
  knn.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  
  print('K = {}'.format(k))
  print('Confusion Matrix: ')
  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

K = 1
Confusion Matrix: 
[[15  0  0]
 [ 0  4  0]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       1.00      1.00      1.00         4
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

K = 3
Confusion Matrix: 
[[15  0  0]
 [ 0  4  0]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       1.00      1.00      1.00         4
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

K = 5
Confusion Matrix: 
[[15  0  0]
 [ 0  4  0]
 [ 0  0 11]]
          